[General]
# Path to the wallpaper. If it's in the assets folder, use "assets/background.jpg"
background=assets/a_video_game_graphics_of_a_forest_and_a_lake.png

# Material You-like colors (we can refine these)
primaryColor=#DCE0E3
accentColor=#8FA9C7
backgroundColor=#181A1C
textColor=#DCE0E3

# Font settings
fontFamily=Google Sans Flex Freeze
fontSize=12
